var annotated =
[
    [ "AIEasy", "class_a_i_easy.html", "class_a_i_easy" ],
    [ "ConnectFour", "class_connect_four.html", "class_connect_four" ],
    [ "ConnectFourAI", "class_connect_four_a_i.html", "class_connect_four_a_i" ],
    [ "ConnectFourLoader", "class_connect_four_loader.html", "class_connect_four_loader" ],
    [ "ConnectFourSaver", "class_connect_four_saver.html", "class_connect_four_saver" ],
    [ "Controls", "class_controls.html", "class_controls" ],
    [ "Coordinate", "class_coordinate.html", "class_coordinate" ],
    [ "Drawing", "class_drawing.html", "class_drawing" ],
    [ "EndDisplay", "class_end_display.html", "class_end_display" ],
    [ "FileManager", "class_file_manager.html", "class_file_manager" ],
    [ "Game", "class_game.html", "class_game" ],
    [ "GameBoardControls", "class_game_board_controls.html", "class_game_board_controls" ],
    [ "GameBoardGraphics", "class_game_board_graphics.html", "class_game_board_graphics" ],
    [ "GameSelecter", "class_game_selecter.html", "class_game_selecter" ],
    [ "GameWindow", "class_game_window.html", "class_game_window" ],
    [ "Grid", "class_grid.html", "class_grid" ],
    [ "Human", "class_human.html", "class_human" ],
    [ "Loader", "class_loader.html", "class_loader" ],
    [ "Othello", "class_othello.html", "class_othello" ],
    [ "OthelloAI", "class_othello_a_i.html", "class_othello_a_i" ],
    [ "OthelloLoader", "class_othello_loader.html", "class_othello_loader" ],
    [ "OthelloSaver", "class_othello_saver.html", "class_othello_saver" ],
    [ "Player", "class_player.html", "class_player" ],
    [ "PlayerSettings", "class_player_settings.html", "class_player_settings" ],
    [ "Saver", "class_saver.html", "class_saver" ],
    [ "TicTacToe", "class_tic_tac_toe.html", "class_tic_tac_toe" ],
    [ "TicTacToeAI", "class_tic_tac_toe_a_i.html", "class_tic_tac_toe_a_i" ],
    [ "TicTacToeLoader", "class_tic_tac_toe_loader.html", "class_tic_tac_toe_loader" ],
    [ "TicTacToeSaver", "class_tic_tac_toe_saver.html", "class_tic_tac_toe_saver" ],
    [ "Timer", "class_timer.html", "class_timer" ]
];