var dir_68267d1309a1af8e8297ef4c3efbcdba =
[
    [ "AIEasy.java", null, null ],
    [ "ConnectFour.java", null, null ],
    [ "ConnectFourAI.java", null, null ],
    [ "ConnectFourLoader.java", null, null ],
    [ "ConnectFourSaver.java", null, null ],
    [ "Controls.java", null, null ],
    [ "Coordinate.java", null, null ],
    [ "Drawing.java", null, null ],
    [ "EndDisplay.java", null, null ],
    [ "FileManager.java", null, null ],
    [ "Game.java", null, null ],
    [ "GameBoardControls.java", null, null ],
    [ "GameBoardGraphics.java", null, null ],
    [ "GameSelecter.java", null, null ],
    [ "GameWindow.java", null, null ],
    [ "Grid.java", null, null ],
    [ "Human.java", null, null ],
    [ "Loader.java", null, null ],
    [ "Othello.java", null, null ],
    [ "OthelloAI.java", null, null ],
    [ "OthelloLoader.java", null, null ],
    [ "OthelloSaver.java", null, null ],
    [ "Player.java", null, null ],
    [ "PlayerSettings.java", null, null ],
    [ "Saver.java", null, null ],
    [ "TicTacToe.java", null, null ],
    [ "TicTacToeAI.java", null, null ],
    [ "TicTacToeLoader.java", null, null ],
    [ "TicTacToeSaver.java", null, null ],
    [ "Timer.java", null, null ]
];